name: queueing
channels:
  - pytorch
  - defaults
dependencies:
  - gymnasium=0.28.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - pip=23.3.1
  - python=3.9.19
  - pytorch=2.2.2
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - scikit-learn=1.3.0
  - scipy=1.12.0
  - seaborn=0.12.2
  - torchaudio=2.2.2
  - torchvision=0.17.2
